In [2]:
import tensorflow as tf
import string
import requests
import pandas as pd

In [41]:
data=pd.read_csv('Train.csv')
data

Unnamed: 0                                               TEXT  Label
0               0  Vacation wasted ! #vacation2017 #photobomb #ti...      0
1               1  Oh Wynwood, you’re so funny! : @user #Wynwood ...      1
2               2  Been friends since 7th grade. Look at us now w...      2
3               3  This is what it looks like when someone loves ...      3
4               4  RT @user this white family was invited to a Bl...      3
...           ...                                                ...    ...
69995       69995  Yes, I call Galina "my Bubie" Go follow my bea...      3
69996       69996    I SEA you, Seattle @ Ballard Seafood Festival\n     16
69997       69997  If one of my daughters is wearing this and ask...      2
69998       69998  Guess who whoop people on THEIR homecoming?! #...      3
69999       69999  We Love you Robbie @ Heritage Memorial Cemeter...     14

[70000 rows x 3 columns]

In [2]:
response=requests.get('http://www.gutenberg.org/cache/epub/10/pg10.txt')

In [42]:

datat=data.TEXT
datat[1]
datat[1]

'Oh Wynwood, you’re so funny! : @user #Wynwood #Art #ItWas3AM #Flowers #Vibes @ Wynwood…\n'

In [44]:
datnew=[]
for d in datat:
    datnew.append(d)

Go to one line of the actual text

In [46]:
datnew

['Vacation wasted ! #vacation2017 #photobomb #tired #vacationwasted #mcgar30 #miami @ Port of…\n',
 'Oh Wynwood, you’re so funny! : @user #Wynwood #Art #ItWas3AM #Flowers #Vibes @ Wynwood…\n',
 'Been friends since 7th grade. Look at us now we all following our dreams doing what we love and…\n',
 'This is what it looks like when someone loves you unconditionally oh Puppy Brother. #htx…\n',
 "RT @user this white family was invited to a Black barbecue and i've never laughed so hard in my life\n",
 "TRACK SEASON 2016, I'M READY FOR YA @ University of the Incarnate Word\n",
 'Merry Christmas you filthy little animals. Wearing a @user ugly sweater featuring Santa…\n',
 'Westenders @user #LAZzNation @ Weston, Toronto\n',
 'Maxwell heads home @ Summa Akron City Hospital\n',
 'Story On Saturday 136 Collins Ave, Miami Beach, FL 33139 Ladies Contact Me To Join Me In my…\n',
 'I love my dog more than most humans @ North Gate\n',
 'Dragged my loving husband to a live episode of #hellofromthemagicta

In [21]:
datat=" ".join(datat)

In [36]:
datat[3]

'This is what it looks like when someone loves you unconditionally oh Puppy Brother. #htx…\n'

Remove punctuations, so on

In [60]:
def clean_text(doc):
    tok=[]
    for c in doc:
        
        tokens=c.split()
        table=str.maketrans('','',string.punctuation)
        tokens=[w.translate(table) for w in tokens]
        tokens=[word for word in tokens if word.isalpha()]
        tokens=[word.lower() for word in tokens]
        tok.append(tokens)
    return tok

In [62]:
tokens=clean_text(datnew)
print(tokens[:100])

[['vacation', 'wasted', 'photobomb', 'tired', 'vacationwasted', 'miami', 'port'], ['oh', 'wynwood', 'so', 'funny', 'user', 'wynwood', 'art', 'flowers', 'vibes'], ['been', 'friends', 'since', 'grade', 'look', 'at', 'us', 'now', 'we', 'all', 'following', 'our', 'dreams', 'doing', 'what', 'we', 'love'], ['this', 'is', 'what', 'it', 'looks', 'like', 'when', 'someone', 'loves', 'you', 'unconditionally', 'oh', 'puppy', 'brother'], ['rt', 'user', 'this', 'white', 'family', 'was', 'invited', 'to', 'a', 'black', 'barbecue', 'and', 'ive', 'never', 'laughed', 'so', 'hard', 'in', 'my', 'life'], ['track', 'season', 'im', 'ready', 'for', 'ya', 'university', 'of', 'the', 'incarnate', 'word'], ['merry', 'christmas', 'you', 'filthy', 'little', 'animals', 'wearing', 'a', 'user', 'ugly', 'sweater', 'featuring'], ['westenders', 'user', 'lazznation', 'weston', 'toronto'], ['maxwell', 'heads', 'home', 'summa', 'akron', 'city', 'hospital'], ['story', 'on', 'saturday', 'collins', 'ave', 'miami', 'beach', 'fl'

In [208]:
tokens[-1:]

[['we', 'love', 'you', 'robbie', 'heritage', 'memorial', 'cemetery', 'llc']]

In [67]:
next=[]
for t in tokens:
    for p in t:
        next.append(p)

In [191]:
next[19:20]

['grade']

number of input+1

In [11]:
lines[0]

'and the earth was without form and void and darkness was upon the face of the deep and the spirit of god moved upon the face of the waters and god said let there be light and there was light and god saw the light that it was good and god'

Building LSTM model

In [76]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [77]:

from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution1D, MaxPooling1D
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

In [81]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(tokens)
sequences=tokenizer.texts_to_sequences(tokens)

In [82]:
sequences=np.array(sequences)

In [83]:
sequences[:50]

array([list([608, 5757, 4889, 1666, 20802, 146, 1313]),
       list([210, 1291, 19, 593, 2, 1291, 203, 1333, 468]),
       list([128, 92, 469, 1894, 107, 16, 84, 90, 23, 28, 2292, 32, 624, 399, 63, 23, 14]),
       list([13, 15, 63, 22, 403, 53, 40, 448, 347, 9, 9010, 210, 977, 489]),
       list([1090, 2, 13, 297, 68, 27, 5266, 4, 5, 436, 5758, 7, 253, 135, 4300, 19, 345, 8, 3, 72]),
       list([1213, 304, 46, 164, 11, 301, 66, 10, 1, 13882, 1588]),
       list([170, 50, 9, 3847, 64, 1851, 829, 5, 2, 1160, 1773, 1370]),
       list([20803, 2, 20804, 3848, 321]),
       list([7842, 3482, 85, 6266, 4301, 61, 1115]),
       list([830, 18, 228, 4076, 1292, 146, 45, 451, 324, 2172, 20, 4, 671, 20, 8]),
       list([6, 14, 3, 530, 89, 165, 231, 4302, 163, 1116]),
       list([10842, 3, 416, 1047, 4, 5, 184, 1818, 10, 20805, 4563, 79]),
       list([110, 186, 4, 389, 9, 2, 20806, 20807, 6958]),
       list([21, 243, 10843, 54]),
       list([130, 20808, 644, 1, 20809, 13, 503, 24, 487, 32])

In [95]:
newseq=[]
for s in sequences:
    x=range(0,35-len(s))
    for p in x:
        s.append(0)
    newseq.append(s)    
        

In [94]:
newseq=[]
x=0
for s in sequences:
    if len(s)>=x:
        x=len(s)
        
print(x)        

33


In [96]:
newseq[:50]

[[608,
  5757,
  4889,
  1666,
  20802,
  146,
  1313,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [210,
  1291,
  19,
  593,
  2,
  1291,
  203,
  1333,
  468,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [128,
  92,
  469,
  1894,
  107,
  16,
  84,
  90,
  23,
  28,
  2292,
  32,
  624,
  399,
  63,
  23,
  14,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [13,
  15,
  63,
  22,
  403,
  53,
  40,
  448,
  347,
  9,
  9010,
  210,
  977,
  489,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [1090,
  2,
  13,
  297,
  68,
  27,
  5266,
  4,
  5,
  436,
  5758,
  7,
  253,
  135,
  4300,
  19,
  345,
  8,
  3,
  72,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [1213,


In [97]:
label=data.Label

In [104]:
X=newseq

In [114]:
X[0]

array([  608,  5757,  4889,  1666, 20802,   146,  1313,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0])

In [112]:
X = np.array(X)

In [186]:
y[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)

In [188]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

one hot encoding

In [18]:
vocab_size=len(tokenizer.word_index)+1
vocab_size

5628

In [99]:
y=to_categorical(label,num_classes=20)

In [100]:
y[:1]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [192]:
seq_length=X.shape[1]
seq_length


35

In [160]:
X.shape

(70000, 35)

In [181]:
vocab_size=len(tokenizer.word_index)+1
vocab_size

68531

LSTM Model

In [182]:
model=Sequential()
#model.add(Embedding(10,50,input_length=35))
#model.add(Conv1D(filters = 64,kernel_size = (3),strides=1,padding='same',data_format='channels_last',input_shape=input_shape))
#model.add(ZeroPadding2D((1,1),input_shape=35))
model.add(Embedding(vocab_size,50,input_length=35))
model.add(Conv1D(128,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPooling1D(pool_size=3))
model.add(Dropout(0.3))
model.add(Conv1D(64,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPooling1D(pool_size=3))
model.add(Dropout(0.35))
model.add(Conv1D(132,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPooling1D(pool_size=3))
model.add(Dropout(0.4))
#model.add(Embedding(vocab_size,50,input_length=seq_length))
model.add(LSTM(100,return_sequences=True))
model.add(LSTM(100))
model.add(Dense(100,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(20,activation='softmax'))

In [138]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_8 (Embedding)      (None, 35, 50)            500       
_________________________________________________________________
conv1d_24 (Conv1D)           (None, 35, 128)           19328     
_________________________________________________________________
max_pooling1d_24 (MaxPooling (None, 11, 128)           0         
_________________________________________________________________
dropout_24 (Dropout)         (None, 11, 128)           0         
_________________________________________________________________
conv1d_25 (Conv1D)           (None, 11, 64)            24640     
_________________________________________________________________
max_pooling1d_25 (MaxPooling (None, 3, 64)             0         
_________________________________________________________________
dropout_25 (Dropout)         (None, 3, 64)            

In [183]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [190]:
model.fit(X_train, y_train,batch_size=256,validation_data=(X_test,y_test),epochs=50)

Epoch 1/50
219/219 [==============================] - 29s 130ms/step - loss: 0.1078 - accuracy: 0.5184 - val_loss: 0.1033 - val_accuracy: 0.5376
Epoch 2/50
219/219 [==============================] - 26s 121ms/step - loss: 0.1016 - accuracy: 0.5473 - val_loss: 0.1059 - val_accuracy: 0.5246
Epoch 3/50
219/219 [==============================] - 26s 121ms/step - loss: 0.0968 - accuracy: 0.5697 - val_loss: 0.1090 - val_accuracy: 0.5169
Epoch 4/50
219/219 [==============================] - 26s 120ms/step - loss: 0.0929 - accuracy: 0.5890 - val_loss: 0.1136 - val_accuracy: 0.4986
Epoch 5/50
219/219 [==============================] - 26s 119ms/step - loss: 0.0891 - accuracy: 0.6096 - val_loss: 0.1164 - val_accuracy: 0.4914
Epoch 6/50
219/219 [==============================] - 26s 119ms/step - loss: 0.0857 - accuracy: 0.6281 - val_loss: 0.1218 - val_accuracy: 0.4661
Epoch 7/50
219/219 [==============================] - 26s 121ms/step - loss: 0.0821 - accuracy: 0.6449 - val_loss: 0.1270 - val_ac

In [197]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(tokens)
sequences=tokenizer.texts_to_sequences(tokens)

In [219]:
tokens[-10:-9]

[['just',
  'because',
  'my',
  'wrestling',
  'career',
  'is',
  'over',
  'doesnt',
  'mean',
  'i',
  'forgot',
  'how',
  'to',
  'scramble',
  'user']]

In [198]:
#Test Sample
tk=[['we', 'love', 'you', 'robbie', 'heritage', 'memorial', 'cemetery', 'llc']]
sequences=np.array(sequences)


In [220]:
n=sequences[-10:-9]

In [216]:
sequences[-4:]

array([list([6, 835, 9, 432, 7818, 1404, 547]),
       list([108, 36, 10, 3, 2679, 15, 829, 13, 7, 3471, 20, 11, 507, 717, 16, 6, 1152, 222, 99]),
       list([486, 112, 10381, 115, 18, 354, 885, 68530, 276, 215]),
       list([23, 14, 9, 10820, 2642, 567, 2276, 1518, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])],
      dtype=object)

In [221]:
newseqtest=[]
for s in n:
    x=range(0,35-len(s))
    for p in x:
        s.append(0)
    newseqtest.append(s)    

In [222]:
sample=newseqtest
sample = np.array(sample)

In [210]:
y = model.predict(sample)
y

array([[5.2183855e-06, 9.4641200e-06, 1.1087012e-04, 4.5333363e-06,
        2.3861397e-05, 1.1493002e-04, 4.4885101e-06, 4.7132135e-06,
        3.9146535e-04, 2.8750678e-03, 8.5427717e-05, 3.3568276e-06,
        2.2820841e-06, 1.8879418e-06, 9.9440420e-01, 5.6568865e-04,
        3.6768648e-05, 4.4464527e-05, 1.3110358e-03, 2.4834367e-07]],
      dtype=float32)

In [225]:
ynew = model.predict_classes(sample)

In [226]:
ynew

array([4], dtype=int64)

winking

In [209]:
dataLabel=pd.read_csv('Mapping.csv')
dataLabel

Unnamed: 0 emoticons  number
0            0         😜       0
1            1         📸       1
2            2         😍       2
3            3         😂       3
4            4         😉       4
5            5         🎄       5
6            6         📷       6
7            7         🔥       7
8            8         😘       8
9            9         ❤       9
10          10         😁      10
11          11        🇺🇸      11
12          12         ☀      12
13          13         ✨      13
14          14         💙      14
15          15         💕      15
16          16         😎      16
17          17         😊      17
18          18         💜      18
19          19         💯      19

In [227]:
model.save('Emoji_Prediction')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: Emoji_Prediction\assets
